### ISSUE TITLE
Pixel 6a (bluejay) support

### ISSUE THREAD

**Issue by luke-jr** [chriswoope/resign-android-image#11]
`grapheneos-otacerts/` is missing a bluejay.pem

Ignoring that, it fails with:
```
   ERROR: Failed to run signapk.jar: return code 1:
java.io.FileNotFoundException: keys/releasekey.x509.pem (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at com.android.signapk.SignApk.readPublicKey(SignApk.java:187)
        at com.android.signapk.SignApk.main(SignApk.java:1127)
```

**Comment by yatraben** [comment]
Bump! Is this still being supported? Because I've seen rarely an answer from the developer, lately..

Is it even safe to try to install it on a device?
